package io.github.adamelliotfields;

import java.io.IOException;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public static void main(String[] args) {
    try {
      CSVPrinter printer = new CSVPrinter(System.out, CSVFormat.DEFAULT);
      printer.printRecord("Adam", "Fields", 5, "Loved It!");
      printer.printRecord("Adam", "Fields", 1, "Hated It!");
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
