[#ftl]
[#function getTemplate springMacroRequestContext]
  [#local uri = springMacroRequestContext.requestUri]
  [#if uri == "/"]
    [#return "Index"]
  [#elseif uri = "/gifs/favorites"]
    [#return "Favorites"]
  [#elseif uri?matches("/gifs/[a-zA-Z0-9]*")]
    [#return "Gif"]
  [/#if]
[/#function]
